package com.neutron.pptfx

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.io.File

/** reverse to */
public infix fun <A, B> A.ot(that: B): Pair<B, A> = Pair(that, this)

val booksEN = mapOf(
    "GEN" ot "Genesis",
    "EXO" ot "Exodus",
    "LEV" ot "Leviticus",
    "NUM" ot "Numbers",
    "DEU" ot "Deuteronomy",
    "JOS" ot "Joshua",
    "JDG" ot "Judges",
    "RUT" ot "Ruth",
    "1SA" ot "1 Samuel",
    "2SA" ot "2 Samuel",
    "1KI" ot "1 Kings",
    "2KI" ot "2 Kings",
    "1CH" ot "1 Chronicles",
    "2CH" ot "2 Chronicles",
    "EZR" ot "Ezra",
    "NEH" ot "Nehemiah",
    "EST" ot "Esther",
    "JOB" ot "Job",
    "PSA" ot "Psalms",
    "PRO" ot "Proverbs",
    "ECC" ot "Ecclesiastes",
    "SNG" ot "Song of Solomon",
    "ISA" ot "Isaiah",
    "JER" ot "Jeremiah",
    "LAM" ot "Lamentations",
    "EZK" ot "Ezekiel",
    "DAN" ot "Daniel",
    "HOS" ot "Hosea",
    "JOL" ot "Joel",
    "AMO" ot "Amos",
    "OBA" ot "Obadiah",
    "JON" ot "Jonah",
    "MIC" ot "Micah",
    "NAM" ot "Nahum",
    "HAB" ot "Habakkuk",
    "ZEP" ot "Zephaniah",
    "HAG" ot "Haggai",
    "ZEC" ot "Zechariah",
    "MAL" ot "Malachi",
    "MAT" ot "Matthew",
    "MRK" ot "Mark",
    "LUK" ot "Luke",
    "JHN" ot "John",
    "ACT" ot "Acts",
    "ROM" ot "Romans",
    "1CO" ot "1 Corinthians",
    "2CO" ot "2 Corinthians",
    "GAL" ot "Galatians",
    "EPH" ot "Ephesians",
    "PHP" ot "Philippians",
    "COL" ot "Colossians",
    "1TH" ot "1 Thessalonians",
    "2TH" ot "2 Thessalonians",
    "1TI" ot "1 Timothy",
    "2TI" ot "2 Timothy",
    "TIT" ot "Titus",
    "PHM" ot "Philemon",
    "HEB" ot "Hebrews",
    "JAS" ot "James",
    "1PE" ot "1 Peter",
    "2PE" ot "2 Peter",
    "1JN" ot "1 John",
    "2JN" ot "2 John",
    "3JN" ot "3 John",
    "JUD" ot "Jude",
    "REV" ot "Revelation")

val booksHU = mapOf(
    "GEN" ot "1Mózes",
    "EXO" ot "2Mózes",
    "LEV" ot "3Mózes",
    "NUM" ot "4Mózes",
    "DEU" ot "5Mózes",
    "JOS" ot "Józsué",
    "JDG" ot "Bírák",
    "RUT" ot "Ruth",
    "1SA" ot "1Sámuel",
    "2SA" ot "2Sámuel",
    "1KI" ot "1Királyok",
    "2KI" ot "2Királyok",
    "1CH" ot "1Krónikák",
    "2CH" ot "2Krónikák",
    "EZR" ot "Ezsdrás",
    "NEH" ot "Nehémiás",
    "EST" ot "Eszter",
    "JOB" ot "Jób",
    "PSA" ot "Zsoltárok",
    "PRO" ot "Példabeszédek",
    "ECC" ot "Prédiktor",
    "SNG" ot "Énekek éneke",
    "ISA" ot "Ézsaiás",
    "JER" ot "Jeremiás",
    "LAM" ot "Jeremiás siralmai",
    "EZK" ot "Ezékiel",
    "DAN" ot "Dániel",
    "HOS" ot "Hóseás",
    "JOL" ot "Jóel",
    "AMO" ot "Ámósz",
    "OBA" ot "Abdiás",
    "JON" ot "Jónás",
    "MIC" ot "Mikeás",
    "NAM" ot "Náhum",
    "HAB" ot "Habakuk",
    "ZEP" ot "Zofóniás",
    "HAG" ot "Haggeus",
    "ZEC" ot "Zakariás",
    "MAL" ot "Malakiás",
    "MAT" ot "Máté",
    "MRK" ot "Márk",
    "LUK" ot "Lukács",
    "JHN" ot "János",
    "ACT" ot "Apostolok Cselekedetei",
    "ROM" ot "Róma",
    "1CO" ot "1Korinthus",
    "2CO" ot "2Korinthus",
    "GAL" ot "Galata",
    "EPH" ot "Efézus",
    "PHP" ot "Filippi",
    "COL" ot "Kolossé",
    "1TH" ot "1Thesszalonika",
    "2TH" ot "2Thesszalonika",
    "1TI" ot "1Timóteus",
    "2TI" ot "2Timóteus",
    "TIT" ot "Títus",
    "PHM" ot "Filemon",
    "HEB" ot "Zsidók",
    "JAS" ot "Jakab",
    "1PE" ot "1 Péter",
    "2PE" ot "2 Péter",
    "1JN" ot "1 János",
    "2JN" ot "2 János",
    "3JN" ot "3 János",
    "JUD" ot "Júdás",
    "REV" ot "Jelenések")
